spring.application.name=test-java

spring.datasource.url=jdbc:postgresql://localhost:5432/test-java
spring.datasource.username=test-java
spring.datasource.password=test-java

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true